# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push
# env:
  # BUCKET_NAME : "<example-bucket-name>"
  # AWS_REGION : "ap-northeast-1"
# permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  accessAWSTest:
    runs-on: ubuntu-latest
    steps:
      - name: Test Access AWS
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2     # default
          verbose: false # default
          arch: amd64    # allowed values: amd64, arm64
          rootdir: ""    # defaults to "PWD"
          workdir: ""    # defaults to "PWD/unfor19-awscli"
      - run: aws iam list-users
        shell: bash
